// Code generated by protoc-gen-go. DO NOT EDIT.
// source: article.proto

package protoFile

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//article
type Article struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tags                 []string           `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Largeclass           string             `protobuf:"bytes,3,opt,name=largeclass,proto3" json:"largeclass,omitempty"`
	Mediumclass          string             `protobuf:"bytes,4,opt,name=mediumclass,proto3" json:"mediumclass,omitempty"`
	Smallclass           string             `protobuf:"bytes,5,opt,name=smallclass,proto3" json:"smallclass,omitempty"`
	Datpublis            string             `protobuf:"bytes,6,opt,name=datpublis,proto3" json:"datpublis,omitempty"`
	Vc2Type              string             `protobuf:"bytes,7,opt,name=vc2type,proto3" json:"vc2type,omitempty"`
	Finalscore           float64            `protobuf:"fixed64,8,opt,name=finalscore,proto3" json:"finalscore,omitempty"`
	Computescore         map[string]float64 `protobuf:"bytes,9,rep,name=computescore,proto3" json:"computescore,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	Servertag            string             `protobuf:"bytes,10,opt,name=servertag,proto3" json:"servertag,omitempty"`
	RecommendTimeLimit   int64              `protobuf:"varint,11,opt,name=recommendTimeLimit,proto3" json:"recommendTimeLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{0}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Article) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Article) GetLargeclass() string {
	if m != nil {
		return m.Largeclass
	}
	return ""
}

func (m *Article) GetMediumclass() string {
	if m != nil {
		return m.Mediumclass
	}
	return ""
}

func (m *Article) GetSmallclass() string {
	if m != nil {
		return m.Smallclass
	}
	return ""
}

func (m *Article) GetDatpublis() string {
	if m != nil {
		return m.Datpublis
	}
	return ""
}

func (m *Article) GetVc2Type() string {
	if m != nil {
		return m.Vc2Type
	}
	return ""
}

func (m *Article) GetFinalscore() float64 {
	if m != nil {
		return m.Finalscore
	}
	return 0
}

func (m *Article) GetComputescore() map[string]float64 {
	if m != nil {
		return m.Computescore
	}
	return nil
}

func (m *Article) GetServertag() string {
	if m != nil {
		return m.Servertag
	}
	return ""
}

func (m *Article) GetRecommendTimeLimit() int64 {
	if m != nil {
		return m.RecommendTimeLimit
	}
	return 0
}

func init() {
	proto.RegisterType((*Article)(nil), "protoFile.Article")
	proto.RegisterMapType((map[string]float64)(nil), "protoFile.Article.ComputescoreEntry")
}

func init() { proto.RegisterFile("article.proto", fileDescriptor_5c593d380f9840a2) }

var fileDescriptor_5c593d380f9840a2 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0xf4, 0x30,
	0x10, 0xc6, 0x69, 0xbb, 0x7f, 0xde, 0x4e, 0x5f, 0x45, 0x07, 0x0f, 0x41, 0x44, 0x8a, 0x78, 0xe8,
	0xa9, 0x87, 0xf5, 0x22, 0x5e, 0x44, 0x45, 0xf1, 0xe0, 0xa9, 0x78, 0xf2, 0x96, 0x4d, 0xc7, 0x25,
	0x98, 0x6c, 0x4b, 0x92, 0x2e, 0xec, 0xb7, 0xf3, 0xa3, 0x49, 0x93, 0x75, 0x5b, 0xd1, 0x53, 0x66,
	0x9e, 0xe7, 0x97, 0xc9, 0x64, 0x06, 0x0e, 0xb8, 0x71, 0x52, 0x28, 0x2a, 0x5b, 0xd3, 0xb8, 0x06,
	0x53, 0x7f, 0x3c, 0x49, 0x45, 0x17, 0x9f, 0x09, 0xcc, 0xef, 0x82, 0x89, 0x87, 0x10, 0xcb, 0x9a,
	0x45, 0x79, 0x54, 0xa4, 0x55, 0x2c, 0x6b, 0x44, 0x98, 0x38, 0xbe, 0xb2, 0x2c, 0xce, 0x93, 0x22,
	0xad, 0x7c, 0x8c, 0xe7, 0x00, 0x8a, 0x9b, 0x15, 0x09, 0xc5, 0xad, 0x65, 0x89, 0x67, 0x47, 0x0a,
	0xe6, 0x90, 0x69, 0xaa, 0x65, 0xa7, 0x03, 0x30, 0xf1, 0xc0, 0x58, 0xea, 0x2b, 0x58, 0xcd, 0x95,
	0x0a, 0xc0, 0x34, 0x54, 0x18, 0x14, 0x3c, 0x83, 0xb4, 0xe6, 0xae, 0xed, 0x96, 0x4a, 0x5a, 0x36,
	0xf3, 0xf6, 0x20, 0x20, 0x83, 0xf9, 0x46, 0x2c, 0xdc, 0xb6, 0x25, 0x36, 0xf7, 0xde, 0x77, 0xda,
	0xd7, 0x7d, 0x97, 0x6b, 0xae, 0xac, 0x68, 0x0c, 0xb1, 0x7f, 0x79, 0x54, 0x44, 0xd5, 0x48, 0xc1,
	0x67, 0xf8, 0x2f, 0x1a, 0xdd, 0x76, 0x8e, 0x02, 0x91, 0xe6, 0x49, 0x91, 0x2d, 0x2e, 0xcb, 0xfd,
	0x2c, 0xca, 0xdd, 0x1c, 0xca, 0x87, 0x11, 0xf6, 0xb8, 0x76, 0x66, 0x5b, 0xfd, 0xb8, 0xd9, 0x77,
	0x68, 0xc9, 0x6c, 0xc8, 0x38, 0xbe, 0x62, 0x10, 0x3a, 0xdc, 0x0b, 0x58, 0x02, 0x1a, 0x12, 0x8d,
	0xd6, 0xb4, 0xae, 0x5f, 0xa5, 0xa6, 0x17, 0xa9, 0xa5, 0x63, 0x59, 0x1e, 0x15, 0x49, 0xf5, 0x87,
	0x73, 0x7a, 0x0b, 0xc7, 0xbf, 0x1e, 0xc4, 0x23, 0x48, 0x3e, 0x68, 0xbb, 0xdb, 0x45, 0x1f, 0xe2,
	0x09, 0x4c, 0x37, 0x5c, 0x75, 0xc4, 0x62, 0xff, 0xb3, 0x90, 0xdc, 0xc4, 0xd7, 0xd1, 0x7d, 0xf6,
	0x36, 0xec, 0x73, 0x39, 0xf3, 0xe1, 0xd5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0x7a, 0xb8,
	0xfe, 0xf2, 0x01, 0x00, 0x00,
}
